### ISSUE TITLE
Cannot build vizdoom on ubuntu 16.04

### ISSUE THREAD

**Issue by CD1010** [mwydmuch/ViZDoom#266]
I keep getting this error when trying to build vizdoom on ubuntu 16.04
I have gym and anaconda3 python 3.6 version installed.

Any clue?  Not sure what is missing.

[ 99%] Linking CXX executable ../../../bin/vizdoom
CMakeFiles/vizdoom.dir/tempfiles.cpp.o: In function `FTempFileName::FTempFileName(char const*)':
tempfiles.cpp:(.text+0x7): warning: the use of `tempnam' is dangerous, better use `mkstemp'
/home/chris/anaconda3/lib/libpng16.so.16: undefined reference to `inflateValidate@ZLIB_1.2.9'
/home/chris/anaconda3/lib/libharfbuzz.so.0: undefined reference to `FT_Get_Var_Blend_Coordinates'
collect2: error: ld returned 1 exit status
src/vizdoom/src/CMakeFiles/vizdoom.dir/build.make:8920: recipe for target 'bin/vizdoom' failed
make[2]: *** [bin/vizdoom] Error 1
CMakeFiles/Makefile2:937: recipe for target 'src/vizdoom/src/CMakeFiles/vizdoom.dir/all' failed
make[1]: *** [src/vizdoom/src/CMakeFiles/vizdoom.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Miffyli** [comment]
I am not too familiar with anaconda and similar systems, but there has been some issues installing VizDoom on those in the past (e.g. #231 ), but they should be fixed by now. You could check those discussions if you find anything that helps you.

**Comment by mwydmuch** [comment]
Hi @CD1010 
I've googled a bit, and it looks like a problem with libpng inside Anaconda required by zlib. But I don't know why cmake links to some version included within Anaconda in your case.

Did you installed all dependencies? (https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md#linux_deps)

Could you post a log from cmake?

**Comment by guiambros** [comment]
I also had a ton of problems building VizDoom with Python 3. Eventually I got it to run, but it was so painful that I decided to use Docker as my official dev environment. See #265.

**Comment by CD1010** [comment]
Thanks, i'll take a look
    On Saturday, December 16, 2017, 10:33:35 PM EST, Gui Ambros <notifications@github.com> wrote:  
 
 
I also had a ton of problems building VizDoom with Python 3. Eventually I got it to run, but it was so painful that I decided to use Docker as my official dev environment. See #265.

**Comment by mwydmuch** [comment]
Fixed some time ago.

**Comment by kuanting** [comment]
Hi, I still ran into the same problem. I can't install VizDoom with pip nor luarocks. I also cloned the github and tried "sudo pip install ." but still failed. Please help.
